/**
 * Tenant Database Schemas — Public Barrel
 *
 * File: apps/api/src/db/tenant/schemas/index.ts
 *
 * Re-exports all Drizzle ORM schema definitions for the tenant database.
 * Consumed by migrations, service layer, and route handlers.
 */

export * from './attempt-questions.schema'
export * from './attempt-start-idempotency-claims.schema'
export * from './attempts.schema'
export * from './backoffice-role-module-permissions.schema'
export * from './backoffice-roles.schema'
export * from './backoffice-staff-users.schema'
export * from './basket-questions.schema'
export * from './baskets.schema'
export * from './categories.schema'
export * from './category-divisions.schema'
export * from './category-subjects.schema'
export * from './category-value-divisions.schema'
export * from './category-value-subjects.schema'
export * from './category-values.schema'
export * from './departments.schema'
export * from './divisions.schema'
export * from './grading-overrides.schema'
export * from './grading-question-results.schema'
export * from './grading-results.schema'
export * from './groups.schema'
export * from './hierarchy-nodes.schema'
export * from './mcq-exam-auto-criteria.schema'
export * from './mcq-exam-questions.schema'
export * from './mcq-exam-settings.schema'
export * from './mcq-exams.schema'
export * from './mcq-question-baskets.schema'
export * from './mcq-question-categories.schema'
export * from './mcq-question-options.schema'
export * from './mcq-question-tags.schema'
export * from './mcq-questions.schema'
export * from './plans.schema'
export * from './rbac-audit-logs.schema'
export * from './scheduled-exams.schema'
export * from './semesters.schema'
export * from './staff-departments.schema'
export * from './staff-divisions.schema'
export * from './staff-groups.schema'
export * from './staff-hierarchy-levels.schema'
export * from './staff-teams.schema'
export * from './students.schema'
export * from './subjects.schema'
export * from './subscriptions.schema'
export * from './tag-relations.schema'
export * from './tags.schema'
export * from './team-types.schema'
export * from './teams.schema'
export * from './translation-audit-logs.schema'
export * from './translations.schema'
export * from './workspace-settings.schema'
