/**
 * @script generate-script-docs
 * @domain generate
 * @description Walk scripts/**\/*.ts, parse @script metadata headers, generate docs/scripts/ pages
 *   and SCRIPT_REGISTRY.md. Exits 1 on naming convention violations.
 * @mode manual,ci
 * @dependencies node:fs,node:path,node:crypto
 */

import { randomUUID } from 'node:crypto'
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { createLogger } from '../core/logger-factory'

const correlationId = randomUUID()
const logger = createLogger('generate-script-docs')
logger.setContext({ correlationId })

const REPO_ROOT = process.cwd()
const SCRIPTS_DIR = join(REPO_ROOT, 'scripts')
const DOCS_DIR = join(REPO_ROOT, 'docs/scripts')

/** @script keys exempt from domain:action naming validation */
const LEGACY_ALLOWLIST = new Set([
  'generate-script-docs',
  'validate-runtime-scripts',
  'seed-dashboard-test-data',
])

/** Validates <domain>:<action> pattern */
const DOMAIN_ACTION_RE = /^[a-z][a-z0-9]+:[a-z][a-z0-9-]+$/

interface ScriptMeta {
  script: string
  domain: string
  description: string
  mode: string
  dependencies: string
  filePath: string
}

function walkTsFiles(dir: string, excludeDirs: string[] = ['__tests__']): string[] {
  const files: string[] = []
  try {
    for (const entry of readdirSync(dir)) {
      if (excludeDirs.includes(entry)) continue
      const full = join(dir, entry)
      let stat: ReturnType<typeof statSync>
      try {
        stat = statSync(full)
      } catch {
        continue
      }
      if (stat.isDirectory()) {
        files.push(...walkTsFiles(full, excludeDirs))
      } else if (entry.endsWith('.ts') && !entry.endsWith('.d.ts')) {
        files.push(full)
      }
    }
  } catch {
    // ignore
  }
  return files
}

function parseMetaHeader(content: string, filePath: string): ScriptMeta | null {
  const scriptMatch = content.match(/@script\s+([^\n*]+)/)
  if (!scriptMatch) return null

  const domainMatch = content.match(/@domain\s+([^\n*]+)/)
  const descMatch = content.match(/@description\s+([^\n*]+)/)
  const modeMatch = content.match(/@mode\s+([^\n*]+)/)
  const depsMatch = content.match(/@dependencies\s+([^\n*]+)/)

  return {
    script: scriptMatch[1].trim(),
    domain: domainMatch ? domainMatch[1].trim() : 'unknown',
    description: descMatch ? descMatch[1].trim() : '',
    mode: modeMatch ? modeMatch[1].trim() : 'manual',
    dependencies: depsMatch ? depsMatch[1].trim() : '',
    filePath: filePath.replace(`${REPO_ROOT}/`, ''),
  }
}

function scriptKeyToDocName(scriptKey: string): string {
  // Convert "db:pool-status" → "db-pool-status"
  return scriptKey.replace(/:/g, '-')
}

function generateDocPage(meta: ScriptMeta): string {
  const docName = scriptKeyToDocName(meta.script)
  const existingDocPath = join(DOCS_DIR, `${docName}.md`)

  // If a hand-authored doc already exists, preserve it but update the header
  if (existsSync(existingDocPath)) {
    const existing = readFileSync(existingDocPath, 'utf-8')
    // Update only the auto-generated metadata comment at top if it exists
    if (existing.startsWith('<!--')) {
      return existing
    }
    // Otherwise return existing content unchanged
    return existing
  }

  // Generate a new doc
  return `# ${meta.script}

<!-- auto-generated by generate-script-docs — edit source @script metadata to update -->

## Command

\`\`\`sh
bun run ${meta.script}
\`\`\`

## Purpose

${meta.description}

## Why It Exists

Generated from \`${meta.filePath}\` metadata header.

## When to Run

Mode: \`${meta.mode}\`

## Execution Mode

${meta.mode}

## Dependencies

${meta.dependencies || 'No external dependencies'}

## Example Usage

\`\`\`sh
bun run ${meta.script}
\`\`\`

## Known Failure Modes

See implementation at \`${meta.filePath}\`.
`
}

function generateRegistry(metas: ScriptMeta[]): string {
  const lines = [
    '# Script Registry',
    '',
    `> Generated: ${new Date().toISOString()}`,
    '',
    '| Script | Domain | Location | Mode | Status |',
    '|--------|--------|----------|------|--------|',
  ]

  for (const meta of metas.sort((a, b) => a.script.localeCompare(b.script))) {
    const docLink = `[${meta.script}](${scriptKeyToDocName(meta.script)}.md)`
    lines.push(
      `| ${docLink} | ${meta.domain} | \`${meta.filePath}\` | ${meta.mode} | ✅ REGISTERED |`
    )
  }

  return `${lines.join('\n')}\n`
}

function main(): void {
  logger.info('Generating script documentation', { scriptsDir: SCRIPTS_DIR, docsDir: DOCS_DIR })

  const tsFiles = walkTsFiles(SCRIPTS_DIR)
  logger.info('TypeScript script files found', { count: tsFiles.length })

  const metas: ScriptMeta[] = []
  const violations: Array<{ script: string; filePath: string; reason: string }> = []

  for (const filePath of tsFiles) {
    let content: string
    try {
      content = readFileSync(filePath, 'utf-8')
    } catch {
      continue
    }

    const meta = parseMetaHeader(content, filePath)
    if (!meta) {
      logger.info('No @script metadata found — skipping', {
        file: filePath.replace(`${REPO_ROOT}/`, ''),
      })
      continue
    }

    // Validate naming convention
    if (!LEGACY_ALLOWLIST.has(meta.script) && !DOMAIN_ACTION_RE.test(meta.script)) {
      violations.push({
        script: meta.script,
        filePath: meta.filePath,
        reason: `"${meta.script}" does not match <domain>:<action> pattern (^[a-z][a-z0-9]+:[a-z][a-z0-9-]+$)`,
      })
      logger.error('Naming convention violation', {
        script: meta.script,
        file: meta.filePath,
        pattern: DOMAIN_ACTION_RE.source,
      })
    }

    metas.push(meta)
  }

  if (violations.length > 0) {
    logger.error('Naming convention violations detected', { violations, count: violations.length })
    process.exit(1)
  }

  // Write docs
  mkdirSync(DOCS_DIR, { recursive: true })
  let written = 0

  for (const meta of metas) {
    const docName = scriptKeyToDocName(meta.script)
    const docPath = join(DOCS_DIR, `${docName}.md`)
    const content = generateDocPage(meta)
    writeFileSync(docPath, content)
    written++
    logger.info('Written doc page', {
      script: meta.script,
      path: docPath.replace(`${REPO_ROOT}/`, ''),
    })
  }

  // Write registry
  const registryPath = join(DOCS_DIR, 'SCRIPT_REGISTRY.md')
  writeFileSync(registryPath, generateRegistry(metas))
  logger.info('Written SCRIPT_REGISTRY.md', { path: registryPath.replace(`${REPO_ROOT}/`, '') })

  logger.info('Script docs generation complete', {
    processed: tsFiles.length,
    withMetadata: metas.length,
    written,
    violations: 0,
  })
}

if (import.meta.main) {
  main()
}
