/**
 * @script dev:generate:script-docs
 * @domain dev
 * @category dev
 * @description Walk scripts/**\/*.ts, parse @script metadata headers, generate
 *   docs/scripts/SCRIPT_REGISTRY.md. Exits 1 on missing required metadata fields.
 * @usage bun run dev:generate:script-docs
 * @mode manual,ci
 * @dependencies node:fs,node:path,node:crypto
 */

import { randomUUID } from 'node:crypto'
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { createLogger } from '../core/logger-factory'

const correlationId = randomUUID()
const logger = createLogger('dev:generate:script-docs')
logger.setContext({ correlationId })

const REPO_ROOT = process.cwd()
const SCRIPTS_DIR = join(REPO_ROOT, 'scripts')
const DOCS_DIR = join(REPO_ROOT, 'docs/scripts')
const REGISTRY_PATH = join(DOCS_DIR, 'SCRIPT_REGISTRY.md')

const ALLOWED_DOMAINS = new Set([
  'db',
  'arch',
  'validate',
  'ai',
  'ci',
  'repo',
  'dev',
  'infra',
  'test',
])

export interface ScriptMeta {
  script: string
  domain: string
  category: string
  description: string
  usage: string
  filePath: string
}

export function walkTsFiles(dir: string, excludeDirs: string[] = ['__tests__']): string[] {
  const files: string[] = []
  try {
    for (const entry of readdirSync(dir)) {
      if (excludeDirs.includes(entry)) continue
      const full = join(dir, entry)
      let stat: ReturnType<typeof statSync>
      try {
        stat = statSync(full)
      } catch {
        continue
      }
      if (stat.isDirectory()) {
        files.push(...walkTsFiles(full, excludeDirs))
      } else if (entry.endsWith('.ts') && !entry.endsWith('.d.ts')) {
        files.push(full)
      }
    }
  } catch {
    // ignore
  }
  return files
}

export function parseMetaHeader(content: string, filePath: string): ScriptMeta | null {
  const scriptMatch = content.match(/@script\s+([^\n*]+)/)
  if (!scriptMatch) return null

  const domainMatch = content.match(/@domain\s+([^\n*]+)/)
  const categoryMatch = content.match(/@category\s+([^\n*]+)/)
  const descMatch = content.match(/@description\s+([\s\S]*?)(?=\s*\*\s*@|\s*\*\/)/)
  const usageMatch = content.match(/@usage\s+([^\n*]+)/)

  return {
    script: scriptMatch[1].trim(),
    domain: domainMatch ? domainMatch[1].trim() : 'unknown',
    category: categoryMatch ? categoryMatch[1].trim() : 'unknown',
    description: descMatch
      ? descMatch[1]
          .split('\n')
          .map((l) => l.replace(/^\s*\*\s?/, '').trim())
          .filter(Boolean)
          .join(' ')
      : '',
    usage: usageMatch ? usageMatch[1].trim() : `bun run ${scriptMatch[1].trim()}`,
    filePath: filePath.replace(`${REPO_ROOT}/`, ''),
  }
}

export function generateRegistry(metas: ScriptMeta[]): string {
  // Sort by domain ASC, then script name ASC
  const sorted = [...metas].sort((a, b) => {
    if (a.domain !== b.domain) return a.domain.localeCompare(b.domain)
    return a.script.localeCompare(b.script)
  })

  // Group by domain
  const byDomain = new Map<string, ScriptMeta[]>()
  for (const meta of sorted) {
    const list = byDomain.get(meta.domain) ?? []
    list.push(meta)
    byDomain.set(meta.domain, list)
  }

  const lines: string[] = [
    '# Zidney Script Registry',
    '',
    '> Auto-generated by `bun run dev:generate:script-docs`. Do not edit manually.',
    `> Last generated: ${new Date().toISOString()}`,
    '',
  ]

  for (const [domain, scripts] of byDomain) {
    lines.push(`## ${domain}`, '')
    lines.push(
      '| Script Name | Source File | Category | Description | Usage |',
      '| ----------- | ----------- | -------- | ----------- | ----- |'
    )
    for (const meta of scripts) {
      lines.push(
        `| \`${meta.script}\` | \`${meta.filePath}\` | ${meta.category} | ${meta.description} | \`${meta.usage}\` |`
      )
    }
    lines.push('')
  }

  return lines.join('\n')
}

function main(): void {
  logger.info('Generating script registry', { scriptsDir: SCRIPTS_DIR })

  if (!existsSync(DOCS_DIR)) {
    mkdirSync(DOCS_DIR, { recursive: true })
  }

  const tsFiles = walkTsFiles(SCRIPTS_DIR)
  logger.info('TypeScript script files found', { count: tsFiles.length })

  const metas: ScriptMeta[] = []
  const violations: string[] = []

  for (const filePath of tsFiles) {
    let content: string
    try {
      content = readFileSync(filePath, 'utf-8')
    } catch {
      continue
    }

    const meta = parseMetaHeader(content, filePath)
    if (!meta) continue

    // Validate required fields
    const missing: string[] = []
    if (!meta.domain || meta.domain === 'unknown') missing.push('@domain')
    if (!meta.category || meta.category === 'unknown') missing.push('@category')
    if (!meta.description) missing.push('@description')
    if (!meta.usage) missing.push('@usage')
    if (meta.domain !== 'unknown' && !ALLOWED_DOMAINS.has(meta.domain))
      missing.push(`@domain="${meta.domain}" (not in allowed set)`)

    if (missing.length > 0) {
      violations.push(
        `  ${filePath.replace(`${REPO_ROOT}/`, '')}\n    Missing: ${missing.join(', ')}`
      )
    }

    metas.push(meta)
  }

  if (violations.length > 0) {
    logger.error('Script metadata violations found', { count: violations.length })
    process.stderr.write(`\n❌ Script metadata violations found: ${violations.length}\n\n`)
    for (const v of violations) {
      process.stderr.write(`${v}\n\n`)
    }
    process.exit(1)
  }

  const registry = generateRegistry(metas)
  writeFileSync(REGISTRY_PATH, registry, 'utf-8')

  logger.info('Registry written', { path: REGISTRY_PATH, scripts: metas.length })
  process.stdout.write(
    `\n✓ Registry written to docs/scripts/SCRIPT_REGISTRY.md (${metas.length} scripts)\n`
  )
}

if (import.meta.main) {
  main()
}
