/**
 * T058: Error Code Enum Definition
 *
 * Purpose: Define all error codes with HTTP status mappings
 * Constitutional Compliance: Standardized error responses
 */

export enum ErrorCode {
  // 4xx Client Errors
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  MISSING_IDEMPOTENCY_KEY = 'MISSING_IDEMPOTENCY_KEY',
  MISSING_FIELD = 'MISSING_FIELD',
  INVALID_FORMAT = 'INVALID_FORMAT',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',

  // 401 Unauthorized
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_JWT = 'INVALID_JWT',

  // 403 Forbidden
  FORBIDDEN = 'FORBIDDEN',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  RBAC_VIOLATION = 'RBAC_VIOLATION',
  WORKSPACE_MISMATCH = 'WORKSPACE_MISMATCH',

  // 404 Not Found
  NOT_FOUND = 'NOT_FOUND',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  ATTEMPT_NOT_FOUND = 'ATTEMPT_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // 409 Conflict
  CONFLICT = 'CONFLICT',
  ATTEMPT_ALREADY_COMPLETED = 'ATTEMPT_ALREADY_COMPLETED',
  ATTEMPT_ALREADY_SUBMITTED = 'ATTEMPT_ALREADY_SUBMITTED',
  INVALID_STATE = 'INVALID_STATE',

  // 410 Gone
  GONE = 'GONE',
  ATTEMPT_EXPIRED = 'ATTEMPT_EXPIRED',

  // 423 Locked
  LOCKED = 'LOCKED',
  WORKSPACE_SOFT_LOCKED = 'WORKSPACE_SOFT_LOCKED',
  LICENSE_SOFT_LOCKED = 'LICENSE_SOFT_LOCKED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',

  // 426 Upgrade Required
  UPGRADE_REQUIRED = 'UPGRADE_REQUIRED',
  SCHEMA_VERSION_INCOMPATIBLE = 'SCHEMA_VERSION_INCOMPATIBLE',

  // 429 Too Many Requests
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // 5xx Server Errors
  INTERNAL_ERROR = 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  REDIS_ERROR = 'REDIS_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  WORKER_UNAVAILABLE = 'WORKER_UNAVAILABLE',
  GRADING_TIMEOUT = 'GRADING_TIMEOUT',

  // Service-specific
  LICENSE_NOT_FOUND = 'LICENSE_NOT_FOUND',
  WORKSPACE_ARCHIVED = 'WORKSPACE_ARCHIVED',
  WORKSPACE_DELETED = 'WORKSPACE_DELETED',
  WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND',
}

/**
 * HTTP Status Code Mapping for Error Codes
 */
export const ERROR_CODE_TO_STATUS: Record<ErrorCode, number> = {
  // 400 Bad Request
  [ErrorCode.BAD_REQUEST]: 400,
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.MISSING_IDEMPOTENCY_KEY]: 400,
  [ErrorCode.MISSING_FIELD]: 400,
  [ErrorCode.INVALID_FORMAT]: 400,
  [ErrorCode.PAYLOAD_TOO_LARGE]: 400,

  // 401 Unauthorized
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.TOKEN_EXPIRED]: 401,
  [ErrorCode.INVALID_JWT]: 401,

  // 403 Forbidden
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.PERMISSION_DENIED]: 403,
  [ErrorCode.RBAC_VIOLATION]: 403,
  [ErrorCode.WORKSPACE_MISMATCH]: 403,

  // 404 Not Found
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.RESOURCE_NOT_FOUND]: 404,
  [ErrorCode.ATTEMPT_NOT_FOUND]: 404,
  [ErrorCode.USER_NOT_FOUND]: 404,
  [ErrorCode.LICENSE_NOT_FOUND]: 404,
  [ErrorCode.WORKSPACE_NOT_FOUND]: 404,

  // 409 Conflict
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.ATTEMPT_ALREADY_COMPLETED]: 409,
  [ErrorCode.ATTEMPT_ALREADY_SUBMITTED]: 409,
  [ErrorCode.INVALID_STATE]: 409,

  // 410 Gone
  [ErrorCode.GONE]: 410,
  [ErrorCode.ATTEMPT_EXPIRED]: 410,

  // 423 Locked
  [ErrorCode.LOCKED]: 423,
  [ErrorCode.WORKSPACE_SOFT_LOCKED]: 423,
  [ErrorCode.LICENSE_SOFT_LOCKED]: 423,
  [ErrorCode.ACCOUNT_LOCKED]: 423,

  // 426 Upgrade Required
  [ErrorCode.UPGRADE_REQUIRED]: 426,
  [ErrorCode.SCHEMA_VERSION_INCOMPATIBLE]: 426,

  // 429 Too Many Requests
  [ErrorCode.TOO_MANY_REQUESTS]: 429,
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,

  // 5xx Server Errors
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.DATABASE_ERROR]: 500,
  [ErrorCode.REDIS_ERROR]: 500,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.WORKER_UNAVAILABLE]: 503,
  [ErrorCode.GRADING_TIMEOUT]: 504,

  // Service-specific
  [ErrorCode.WORKSPACE_ARCHIVED]: 403,
  [ErrorCode.WORKSPACE_DELETED]: 403,
}

/**
 * Get HTTP status code for error code
 */
export function getStatusCode(code: ErrorCode): number {
  return ERROR_CODE_TO_STATUS[code] || 500
}
