/**
 * Scheduled Exam — Error Codes & Classes
 *
 * File: packages/domain-core/src/scheduled-exam/scheduled-exam.errors.ts
 * Stage: STAGE_38_SCHEDULED_EXAM_ENGINE
 */

export const SCHEDULED_EXAM_ERROR_CODES = {
  NOT_FOUND: 'SCHEDULED_EXAM.NOT_FOUND',
  CODE_CONFLICT: 'SCHEDULED_EXAM.CODE_CONFLICT',
  BASE_EXAM_NOT_FOUND: 'SCHEDULED_EXAM.BASE_EXAM_NOT_FOUND',
  INVALID_TIME_WINDOW: 'SCHEDULED_EXAM.INVALID_TIME_WINDOW',
  FIELD_IMMUTABLE: 'SCHEDULED_EXAM.FIELD_IMMUTABLE',
  HAS_ATTEMPTS: 'SCHEDULED_EXAM.HAS_ATTEMPTS',
  WORKFLOW_INVALID_TRANSITION: 'SCHEDULED_EXAM.WORKFLOW_INVALID_TRANSITION',
  NOT_ENABLED: 'SCHEDULED_EXAM.NOT_ENABLED',
  WINDOW_NOT_OPEN: 'SCHEDULED_EXAM.WINDOW_NOT_OPEN',
  ALREADY_ATTEMPTED: 'SCHEDULED_EXAM.ALREADY_ATTEMPTED',
  ATTEMPT_NOT_FOUND: 'SCHEDULED_EXAM.ATTEMPT_NOT_FOUND',
  ATTEMPT_ALREADY_SUBMITTED: 'SCHEDULED_EXAM.ATTEMPT_ALREADY_SUBMITTED',
  RE_APPROVE_NOT_REQUIRED: 'SCHEDULED_EXAM.RE_APPROVE_NOT_REQUIRED',
  BASE_EXAM_MODIFIED: 'SCHEDULED_EXAM.BASE_EXAM_MODIFIED',
} as const

export type ScheduledExamErrorCode =
  (typeof SCHEDULED_EXAM_ERROR_CODES)[keyof typeof SCHEDULED_EXAM_ERROR_CODES]

export const SCHEDULED_EXAM_ERROR_HTTP_STATUS: Record<ScheduledExamErrorCode, number> = {
  [SCHEDULED_EXAM_ERROR_CODES.NOT_FOUND]: 404,
  [SCHEDULED_EXAM_ERROR_CODES.CODE_CONFLICT]: 409,
  [SCHEDULED_EXAM_ERROR_CODES.BASE_EXAM_NOT_FOUND]: 422,
  [SCHEDULED_EXAM_ERROR_CODES.INVALID_TIME_WINDOW]: 422,
  [SCHEDULED_EXAM_ERROR_CODES.FIELD_IMMUTABLE]: 409,
  [SCHEDULED_EXAM_ERROR_CODES.HAS_ATTEMPTS]: 409,
  [SCHEDULED_EXAM_ERROR_CODES.WORKFLOW_INVALID_TRANSITION]: 422,
  [SCHEDULED_EXAM_ERROR_CODES.NOT_ENABLED]: 403,
  [SCHEDULED_EXAM_ERROR_CODES.WINDOW_NOT_OPEN]: 403,
  [SCHEDULED_EXAM_ERROR_CODES.ALREADY_ATTEMPTED]: 409,
  [SCHEDULED_EXAM_ERROR_CODES.ATTEMPT_NOT_FOUND]: 404,
  [SCHEDULED_EXAM_ERROR_CODES.ATTEMPT_ALREADY_SUBMITTED]: 410, // gone: attempt can no longer be resubmitted
  [SCHEDULED_EXAM_ERROR_CODES.RE_APPROVE_NOT_REQUIRED]: 422,
  [SCHEDULED_EXAM_ERROR_CODES.BASE_EXAM_MODIFIED]: 422,
}

export const SCHEDULED_EXAM_ERROR_MESSAGES: Record<ScheduledExamErrorCode, string> = {
  [SCHEDULED_EXAM_ERROR_CODES.NOT_FOUND]: 'Scheduled exam not found',
  [SCHEDULED_EXAM_ERROR_CODES.CODE_CONFLICT]: 'A scheduled exam with this code already exists',
  [SCHEDULED_EXAM_ERROR_CODES.BASE_EXAM_NOT_FOUND]:
    'The base exam referenced does not exist or is not enabled',
  [SCHEDULED_EXAM_ERROR_CODES.INVALID_TIME_WINDOW]:
    'The time window is invalid (end must be after start)',
  [SCHEDULED_EXAM_ERROR_CODES.FIELD_IMMUTABLE]:
    'This field cannot be changed after attempts have started',
  [SCHEDULED_EXAM_ERROR_CODES.HAS_ATTEMPTS]: 'Cannot delete: this exam has associated attempts',
  [SCHEDULED_EXAM_ERROR_CODES.WORKFLOW_INVALID_TRANSITION]:
    'This workflow transition is not allowed',
  [SCHEDULED_EXAM_ERROR_CODES.NOT_ENABLED]: 'The scheduled exam is not enabled — access denied',
  [SCHEDULED_EXAM_ERROR_CODES.WINDOW_NOT_OPEN]: 'The exam window is not currently open',
  [SCHEDULED_EXAM_ERROR_CODES.ALREADY_ATTEMPTED]: 'You have already attempted this exam',
  [SCHEDULED_EXAM_ERROR_CODES.ATTEMPT_NOT_FOUND]: 'Attempt not found',
  [SCHEDULED_EXAM_ERROR_CODES.ATTEMPT_ALREADY_SUBMITTED]: 'Attempt already submitted',
  [SCHEDULED_EXAM_ERROR_CODES.RE_APPROVE_NOT_REQUIRED]:
    'Re-approval is not required (base exam not modified)',
  [SCHEDULED_EXAM_ERROR_CODES.BASE_EXAM_MODIFIED]:
    'Base exam has been modified since approval — re-approval required',
}

export class ScheduledExamError extends Error {
  constructor(
    public readonly code: ScheduledExamErrorCode,
    message?: string
  ) {
    super(message ?? SCHEDULED_EXAM_ERROR_MESSAGES[code] ?? code)
    this.name = 'ScheduledExamError'
  }
}
