/** @library-module */

import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import {
  compareGeneratedDocsFiles,
  findStaleDocFiles,
  generateScriptDoc,
  normalizeGeneratedDocContent,
  parseMetaHeader,
  parsePackageReferenceSections,
  resolveDocFileName,
} from '../script-docs'

describe('parseMetaHeader', () => {
  it('parses a multiline metadata header', () => {
    const content = `/**
 * @script dev:generate:script-docs
 * @domain dev
 * @category dev
 * @description Walk scripts/**/*.ts and generate docs.
 *   Exits non-zero on metadata violations.
 * @usage bun run dev:generate:script-docs
 */
`

    const meta = parseMetaHeader(content, '/repo/scripts/generate/script-docs.ts')
    expect(meta?.script).toBe('dev:generate:script-docs')
    expect(meta?.domain).toBe('dev')
    expect(meta?.description).toContain('Exits non-zero on metadata violations.')
  })
})

describe('parsePackageReferenceSections', () => {
  it('extracts package.md fields used for per-script docs', () => {
    const content = `### arch:guard

- Power: critical
- Purpose: Run architecture guard checks.
- Source: \`scripts/architecture-guard/architecture-guard.ts\`
- CI flag: Dedicated CI runner by name.
- Depends on: \`arch:context:build\`, \`arch:context:validate\`
- Used by other root scripts: \`governance:gate:changed\`
- Updated or generated files: Observed in isolated worktree run: no tracked file changes.
- Removal assessment: Do not remove without updating CI.
`

    const sections = parsePackageReferenceSections(content)
    const section = sections.get('arch:guard')

    expect(section?.purpose).toBe('Run architecture guard checks.')
    expect(section?.dependsOn).toEqual(['arch:context:build', 'arch:context:validate'])
    expect(section?.usedBy).toEqual(['governance:gate:changed'])
  })
})

describe('resolveDocFileName', () => {
  it('preserves an existing legacy doc filename when present', () => {
    expect(resolveDocFileName('dev:generate:script-docs', 'generate-script-docs.md')).toBe(
      'generate-script-docs.md'
    )
  })

  it('falls back to a colon-to-hyphen normalized filename', () => {
    expect(resolveDocFileName('arch:context:build')).toBe('arch-context-build.md')
  })
})

describe('findStaleDocFiles', () => {
  it('filters orphaned generated docs while preserving reserved files', () => {
    expect(
      findStaleDocFiles(
        [
          'README.md',
          'SCRIPT_REGISTRY.md',
          'SCRIPT_MIGRATION_MAP.md',
          'repo-script.md',
          'dev-demo-logger-features.md',
          'repo-status.md',
        ],
        ['repo-status.md']
      )
    ).toEqual(['repo-script.md', 'dev-demo-logger-features.md'])
  })
})

describe('check-only helpers', () => {
  it('ignores the registry timestamp when comparing generated content', () => {
    const filePath = '/repo/docs/scripts/SCRIPT_REGISTRY.md'
    const existing = `# Zidney Script Registry

> Auto-generated by \`bun run dev:generate:script-docs\`. Do not edit manually.
> Last generated: 2026-04-01T00:00:00.000Z
`
    const expected = `# Zidney Script Registry

> Auto-generated by \`bun run dev:generate:script-docs\`. Do not edit manually.
> Last generated: 2026-04-02T00:00:00.000Z
`

    expect(normalizeGeneratedDocContent(filePath, existing)).toBe(
      normalizeGeneratedDocContent(filePath, expected)
    )
  })

  it('treats escaped markdown wildcards as equivalent during comparison', () => {
    const filePath = '/repo/docs/scripts/prepare.md'
    const existing = '- Implementation: Wrapper only; no single scripts/\\*.ts source file.\n'
    const expected = '- Implementation: Wrapper only; no single scripts/*.ts source file.\n'

    expect(normalizeGeneratedDocContent(filePath, existing)).toBe(
      normalizeGeneratedDocContent(filePath, expected)
    )
  })

  it('reports missing, changed, and stale docs during check-only validation', () => {
    const repoRoot = mkdtempSync(join(tmpdir(), 'script-docs-'))

    try {
      mkdirSync(join(repoRoot, 'docs/scripts'), { recursive: true })
      const existingPath = join(repoRoot, 'docs/scripts/README.md')
      writeFileSync(existingPath, '# stale contents\n', 'utf-8')

      const expectedFiles = new Map<string, string>([
        [existingPath, '# fresh contents\n'],
        [join(repoRoot, 'docs/scripts/SCRIPT_REGISTRY.md'), '# registry\n'],
      ])

      expect(
        compareGeneratedDocsFiles(expectedFiles, ['docs/scripts/orphaned.md'], repoRoot)
      ).toEqual({
        missingFiles: ['docs/scripts/SCRIPT_REGISTRY.md'],
        changedFiles: ['docs/scripts/README.md'],
        staleFiles: ['docs/scripts/orphaned.md'],
      })
    } finally {
      rmSync(repoRoot, { recursive: true, force: true })
    }
  })
})

describe('generateScriptDoc', () => {
  it('renders a page for a root wrapper using package reference data', () => {
    const page = generateScriptDoc({
      script: 'arch:guard',
      command: 'bun scripts/architecture-guard/architecture-guard.ts',
      filePath: 'arch-guard.md',
      sourcePath: 'scripts/architecture-guard/architecture-guard.ts',
      dependsOn: ['arch:context:build'],
      usedBy: ['governance:gate:changed'],
      reference: {
        power: 'critical',
        purpose: 'Run architecture guard checks.',
        source: '`scripts/architecture-guard/architecture-guard.ts`',
        ciFlag: 'Dedicated CI runner by name.',
        updatedGeneratedFiles: 'Observed in isolated worktree run: no tracked file changes.',
        removalAssessment: 'Do not remove without updating CI.',
        dependsOn: ['arch:context:build'],
        usedBy: ['governance:gate:changed'],
      },
      meta: undefined,
    })

    expect(page).toContain('# arch:guard')
    expect(page).toContain('bun run arch:guard')
    expect(page).toContain('Run architecture guard checks.')
    expect(page).toContain('Dedicated CI runner by name.')
    expect(page).toContain('`arch:context:build`')
    expect(page).toContain('`governance:gate:changed`')
    expect(page).toContain('- Package runner: `bun run arch:guard`')
    expect(page).not.toContain('Registered package.json runner:')
  })

  it('renders the wrapper-only source line using markdown-safe wildcard escaping', () => {
    const page = generateScriptDoc({
      script: 'prepare',
      command: 'husky',
      filePath: 'prepare.md',
      sourcePath: undefined,
      dependsOn: [],
      usedBy: [],
      reference: undefined,
      meta: undefined,
    })

    expect(page).toContain('Implementation: Wrapper only; no single scripts/\\*.ts source file.')
  })
})
