#!/usr/bin/env bun
/**
 * GitHub Actions Cache Configuration (T068)
 *
 * Purpose: Document and validate GitHub Actions caching strategy for AI context artifacts
 *
 * Strategy (Q1):
 * - Cache selective artifacts: dependency-graph and runtime-dependents (hotspots)
 * - Use GitHub Actions cache with hash-based invalidation
 * - Cache key: include package.json + tsconfig.json hash for auto-invalidation
 * - Cache paths: docs/ai/context/.cache/
 *
 * Expected Improvements (from clarification Q2):
 * - Dependency-graph generation: 2.5s → <500ms (cache hit)
 * - Runtime-dependents generation: 2s → <400ms (cache hit)
 * - Overall ai-context generation: 5-8s → <2s (with cache)
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { createLogger, flushAi, log } from '../utils/logger'

const logger = createLogger('github-actions-cache-config')

interface CacheConfig {
  enabled: boolean
  artifact_types: string[]
  cache_key_strategy: {
    primary_inputs: string[]
    hash_algorithm: string
    example_key: string
  }
  cache_paths: string[]
  ttl_seconds: number
  expected_hit_ratio: string
  io_savings_percent: number
}

function generateCacheConfig(): CacheConfig {
  const config: CacheConfig = {
    enabled: true,
    artifact_types: ['dependency-graph', 'runtime-dependents'],
    cache_key_strategy: {
      primary_inputs: [
        'packages/*/package.json',
        'apps/*/package.json',
        'tsconfig.json',
        'tsconfig.base.json',
        'bun.lock',
      ],
      hash_algorithm: 'SHA256',
      example_key: `ai-context-cache-\${{ hashFiles("packages/*/package.json", "apps/*/package.json", "tsconfig.json") }}`,
    },
    cache_paths: ['docs/ai/context/.cache/'],
    ttl_seconds: 86400, // 24 hours
    expected_hit_ratio: '>80%',
    io_savings_percent: 70, // Expected 70% reduction in ai-context generation time with cache hits
  }

  return config
}

function generateWorkflowYaml(): string {
  const yaml = `
# GitHub Actions Cache Strategy for AI Context Artifacts (Phase 3 Q1)
# 
# This workflow demonstrates the cache integration for selective artifact caching
# to reduce CI time and improve developer feedback loop
#

# Cache Step - Add to ai-context-generation job (after checkout and before generation)
- name: Restore AI Context Cache
  uses: actions/cache@v4
  with:
    # Cache files generated by ai-context generation
    path: docs/ai/context/.cache/
    
    # Cache key: invalidates when source files change
    # Hash includes: all package.json files + config files
    key: ai-context-cache-\${{ hashFiles('packages/*/package.json', 'apps/*/package.json', 'tsconfig.json', 'tsconfig.base.json', 'bun.lock') }}
    
    # Fallback key: use latest cache if exact match not found
    restore-keys: |
      ai-context-cache-
    
    # Separate cache per branch (optional, can be set to false for shared cache)
    # Currently false: share cache across branches for maximum hit ratio
    save-always: true

# Next step: Generate AI Context (will use cached artifacts if available)
- name: Generate AI Context Artifacts
  run: bun scripts/generate-ai-context.ts --force --validate

# Validation Step - Verify cache effectiveness
- name: Validate Cache Effectiveness
  run: |
    # Check if cache files exist (indicates cache hit)
    if [ -d "docs/ai/context/.cache" ]; then
      echo "✓ Cache directory exists (hit)"
      find docs/ai/context/.cache -type f -exec ls -lh {} \\;
    else
      echo "✓ Cache miss (first run on branch)"
    fi
`

  return yaml
}

function generateCacheStrategy(): string {
  const strategy = `
# AI Context Artifact Caching Strategy

## Overview
Phase 3 implements selective caching for expensive artifact generation (Q2 strategy).

## Artifacts Strategy
Only cache the two most expensive artifacts:
- \`dependency-graph\`: 2.5s generation time → <500ms with cache (80% improvement)
- \`runtime-dependents\`: 2s generation time → <400ms with cache (80% improvement)

Don't cache:
- \`ai-context-mini.json\`: <100ms generation (too cheap to cache)
- \`ai-module-map.json\`: <200ms generation  
- \`ai-architecture-brain.json\`: composite artifact, regenerated from graph
- Other small artifacts: overhead of cache validation exceeds generation time

## Cache Key Strategy
Use multi-level hashing to detect changes:

### Primary Hash (Full Invalidation)
Inputs: All package.json files in packages/ and apps/, plus core config files
- If any module's package.json changes → cache invalidates
- If TypeScript config changes → cache invalidates  
- If bun.lock changes → cache invalidates

### Hash Format
\`ai-context-cache-{SHA256(files)}\`

Example: \`ai-context-cache-a1b2c3d4e5f6...\`

## Cache Behavior

### Cold Run (First execution after branch creation)
1. No cache found for this hash
2. Generate all artifacts from scratch
3. Save generated artifacts to cache
4. Duration: 5-8 seconds

### Warm Run (Subsequent execution, same hash)
1. Cache found for this hash
2. Load dependency-graph and runtime-dependents from cache
3. Regenerate only non-cached artifacts (mini, brain, etc.)
4. Duration: <2 seconds (70% improvement)

### Cache Invalidation (Source files changed)
1. package.json modified → new hash generated
2. Old cache key no longer matches
3. Generate all artifacts from scratch
4. Save to new cache entry
5. Old cache gradually expires after 7 days (platform default)

## Expected Metrics

### Before (Phase 2)
- Cold build: 5-8 seconds
- Warm build: 5-8 seconds (no cache)
- Total CI time: 12-18 minutes

### After (Phase 3)
- Cold build: 5-8 seconds (first time, no cache)
- Warm build: <2 seconds (70% improvement)
- Total CI time: <8 minutes (25-35% reduction)

### Cache Hit Ratio
- Expected: >80% in dev branches
- This assumes developers don't frequently change module dependencies
- If modules change, cache invalidates (correct behavior)

## Operational Notes

1. **Cache storage:** GitHub provides 5GB free cache per repository
   - AI context artifacts: ~100KB total
   - Expected cache usage: <1MB
   
2. **Cache expiry:** GitHub deletes unused cache after 7 days
   - Not an issue since we regenerate on each build
   - Old caches naturally expire

3. **Cache sharing:** Cache is per-branch by default
   - main branch cache: used by main CI runs
   - feature branches: accumulate own caches
   - Setting \`restore-keys\` allows fallback to main cache

4. **Local Development:** 
   - Cache is stored in \`docs/ai/context/.cache/\`
   - Developers can delete to force regeneration
   - Cache persists across local runs (no 7-day expiration)

## CI Integration Checklist

- [x] T068: Cache configuration documented
- [ ] T069: Add cache restore step to ci.yml
- [ ] T070: Add cache invalidation pattern documentation
- [ ] T071: Test cache effectiveness in CI

## Related Tasks
- T060: Implement cache in dependency-graph-generator
- T061: Implement cache in runtime-dependents-generator
- T062: File hash-based invalidation in cache-manager
- T063: Validate >80% cache hit ratio
`

  return strategy
}

async function main() {
  log.header(
    'CONFIGURE GITHUB ACTIONS CACHE',
    'Documents and validates GitHub Actions caching strategy for AI context artifacts'
  )
  logger.info('Generating GitHub Actions cache configuration...')

  // Create cache config
  const config = generateCacheConfig()

  // Create documentation directory
  mkdirSync('docs/ci-cd-integration', { recursive: true })

  // Write cache configuration
  const configPath = 'docs/ci-cd-integration/CACHE_CONFIGURATION.json'
  writeFileSync(configPath, JSON.stringify(config, null, 2), 'utf-8')
  logger.info('Cache configuration written', { path: configPath })

  // Write cache strategy documentation
  const strategyPath = 'docs/ci-cd-integration/ARTIFACT_CACHING_STRATEGY.md'
  writeFileSync(strategyPath, generateCacheStrategy(), 'utf-8')
  logger.info('Cache strategy documentation written', { path: strategyPath })

  // Write workflow yaml example
  const workflowPath = 'docs/ci-cd-integration/CACHE_WORKFLOW_EXAMPLE.yml'
  writeFileSync(workflowPath, generateWorkflowYaml(), 'utf-8')
  logger.info('Workflow example written', { path: workflowPath })

  // Report
  log.success('GitHub Actions Cache Configuration Generated')
  log.step('Files Created:')
  log.info(`  1. ${configPath}`)
  log.info(`  2. ${strategyPath}`)
  log.info(`  3. ${workflowPath}`)
  log.step('Next Steps:')
  log.info('  \u2022 Review cache strategy in docs/ci-cd-integration/ARTIFACT_CACHING_STRATEGY.md')
  log.info('  \u2022 Apply cache steps from workflow example to .github/workflows/ci.yml')
  log.info('  \u2022 Validate cache effectiveness with validate-cache-effectiveness.ts')

  log.result({ total: 3, passed: 3, failed: 0, message: 'Cache configuration files generated' })
  flushAi()
  process.exit(0)
}

main().catch((err) => {
  logger.error('Configuration generation failed', { error: String(err) })
  process.exit(1)
})
