/**
 * Zidney Repository Hygiene Report Generator
 * Runs all hygiene checks and writes a structured Markdown report to
 * docs/reports/REPOSITORY_HYGIENE_REPORT.md
 *
 * NOTE-01: rawOutput is sanitized before inclusion — user paths and env vars stripped.
 * NOTE-05: Each check is wrapped in try/catch; exceptions produce INCONCLUSIVE result.
 *          Never exits with code > 0 — report health is communicated via report content.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { flushAi, log } from '../utils/logger'
import { runAiContextCheck } from './hygiene-checks/ai-context-check.ts'
import { runArchGuardCheck } from './hygiene-checks/arch-guard-check.ts'
import { runCiWorkflowCheck } from './hygiene-checks/ci-workflow-check.ts'
import { runDeadScriptCheck } from './hygiene-checks/dead-script-check.ts'
import { runDependencyHygieneCheck } from './hygiene-checks/dependency-hygiene-check.ts'
import { runRoutingAuthorityCheck } from './hygiene-checks/routing-authority-check.ts'
import { runSkillSurfaceCheck } from './hygiene-checks/skill-surface-check.ts'
import { runTemplateConsolidationCheck } from './hygiene-checks/template-consolidation-check.ts'
import type { TaskResult } from './hygiene-checks/types.ts'
import { runWorkspacePackageCheck } from './hygiene-checks/workspace-package-check.ts'

const ROOT = process.cwd()
const REPORT_PATH = join(ROOT, 'docs', 'reports', 'REPOSITORY_HYGIENE_REPORT.md')

// NOTE-01: Sanitize rawOutput — strip absolute user paths and env var assignments
function sanitizeOutput(raw: string | undefined): string {
  if (!raw) return ''

  return raw
    .replace(/\/Users\/[^\s/]+/g, '/REDACTED_HOME')
    .replace(/\/home\/[^\s/]+/g, '/REDACTED_HOME')
    .replace(/\/root\/[^\s/]+/g, '/REDACTED_HOME')
    .replace(/\/runner\/[^\s/]+/g, '/REDACTED_RUNNER')
    .replace(/[A-Z_]+=\S+/g, '[ENV]')
    .substring(0, 2000)
}

// NOTE-05: Wrap each check so errors produce INCONCLUSIVE rather than crashing
async function safeRun(label: string, fn: () => Promise<TaskResult>): Promise<TaskResult> {
  try {
    return await fn()
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    return {
      taskId: label,
      title: label,
      status: 'INCONCLUSIVE',
      summary: `Check threw an unexpected error: ${message}`,
      findings: [],
    }
  }
}

function statusIcon(status: TaskResult['status']): string {
  switch (status) {
    case 'PASS':
      return '✅'
    case 'FLAG':
      return '⚑'
    case 'WARNING':
      return '⚠️'
    case 'SKIP':
      return '⏭'
    case 'INCONCLUSIVE':
      return '❓'
    default:
      return '—'
  }
}

function renderResult(result: TaskResult): string {
  const icon = statusIcon(result.status)
  const lines: string[] = []

  lines.push(`### ${icon} ${result.title} \`[${result.status}]\``)
  lines.push('')
  lines.push(`**Summary:** ${result.summary}`)

  if (result.findings.length > 0) {
    lines.push('')
    lines.push('**Findings:**')
    lines.push('')
    for (const f of result.findings.slice(0, 30)) {
      lines.push(`- \`${f.item}\` — ${f.note}`)
    }
    if (result.findings.length > 30) {
      lines.push(`- _…and ${result.findings.length - 30} more_`)
    }
  }

  if (result.rawOutput) {
    const safe = sanitizeOutput(result.rawOutput)
    if (safe.trim()) {
      lines.push('')
      lines.push('<details><summary>Raw output</summary>')
      lines.push('')
      lines.push('```')
      lines.push(safe)
      lines.push('```')
      lines.push('</details>')
    }
  }

  lines.push('')
  return lines.join('\n')
}

function computeOverallVerdict(results: TaskResult[]): string {
  const blocking: TaskResult['status'][] = ['FLAG', 'WARNING', 'INCONCLUSIVE']
  const hasAttention = results.some((r) => blocking.includes(r.status))
  return hasAttention ? 'ATTENTION REQUIRED' : 'CLEAN'
}

function renderReport(results: TaskResult[], generatedAt: string): string {
  const verdict = computeOverallVerdict(results)
  const verdictBadge = verdict === 'CLEAN' ? '✅ CLEAN' : '⚑ ATTENTION REQUIRED'

  const summaryRows = results
    .map((r) => `| ${statusIcon(r.status)} ${r.title} | \`${r.status}\` | ${r.summary} |`)
    .join('\n')

  const sections = results.map(renderResult).join('\n---\n\n')

  return `# Repository Hygiene Report

> **Generated:** ${generatedAt}
> **Overall Verdict:** ${verdictBadge}

---

## Summary Table

| Check | Status | Summary |
|-------|--------|---------|
${summaryRows}

---

## Detailed Results

${sections}

---

_Generated by \`scripts/dev/hygiene-report-generator.ts\`_
`
}

async function main(): Promise<void> {
  const generatedAt = new Date().toISOString()

  log.header(
    'REPOSITORY HYGIENE REPORT',
    'Runs all hygiene checks and writes a structured Markdown report'
  )
  log.step('Running repository hygiene checks...')

  const checks: Array<{ label: string; fn: () => Promise<TaskResult> }> = [
    { label: 'T001', fn: runRoutingAuthorityCheck },
    { label: 'T002', fn: runTemplateConsolidationCheck },
    { label: 'T003', fn: runDeadScriptCheck },
    { label: 'T004', fn: runDependencyHygieneCheck },
    { label: 'T005', fn: runWorkspacePackageCheck },
    { label: 'T006', fn: runSkillSurfaceCheck },
    { label: 'T007', fn: runCiWorkflowCheck },
    { label: 'T008', fn: runAiContextCheck },
    { label: 'T009', fn: runArchGuardCheck },
  ]

  const results: TaskResult[] = []

  for (const { label, fn } of checks) {
    process.stdout.write(`  Running ${label}… `)
    const result = await safeRun(label, fn)
    results.push(result)
    log.info(`  ${statusIcon(result.status)} [${result.status}] ${result.title}`)
  }

  log.step('Generating report...')

  const report = renderReport(results, generatedAt)

  mkdirSync(dirname(REPORT_PATH), { recursive: true })
  writeFileSync(REPORT_PATH, report, 'utf-8')

  const verdict = computeOverallVerdict(results)
  if (verdict === 'CLEAN') {
    log.success('Overall verdict: CLEAN')
  } else {
    log.warn('Overall verdict: ATTENTION REQUIRED')
  }
  log.success(`Report written to: ${REPORT_PATH.replace(ROOT, '.')}`)
  log.result({
    total: results.length,
    passed: results.filter((r) => r.status === 'PASS').length,
    failed: results.filter((r) => r.status === 'FLAG' || r.status === 'WARNING').length,
  })
  flushAi()
  // NOTE-05: Always exit 0 — health communicated via report content
  process.exit(0)
}

main()
